AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template was written for
  running Kittens Carousel Static Website on EC2.
  Honey-Flower Sale Static Website will be
  deployed on Amazon Linux 2
  (ami-05fa00d4c63e32376) EC2 Instance with
  custom security group which allows http
  connections on port 80 and ssh port 22 from
  anywhere. Honey-Flower Sale Static Website
  is downloaded from my Public Github repository,
  then deployed on Apache Web Server.

  
Resources:
  WebServerSecutiryGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server and SSH for secure connection. # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: Zabkey
      SecurityGroupIds:
        - !Ref WebServerSecutiryGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack
      UserData:         
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            FOLDER="https://raw.githubusercontent.com/Zabraham-fab/My-projects/main/Project-101.1-static-website-ec2-Flower-Honey/static-web"
            cd /var/www/html
            wget $FOLDER/index.html
            wget $FOLDER/cat1.jpg
            wget $FOLDER/cat4.jpg
            wget $FOLDER/cat2.jpg
            wget $FOLDER/cat7.jpg
            wget $FOLDER/cat8.jpg
            wget $FOLDER/cat9.jpg
            wget $FOLDER/cat10.jpg
            wget $FOLDER/cat11.jpg
            wget $FOLDER/com.jpg
            wget $FOLDER/er0.jpg
            wget $FOLDER/erz1.jpg
            wget $FOLDER/hon.jpg
            wget $FOLDER/hon1.jpg
            wget $FOLDER/hon2.jpg
            wget $FOLDER/hon3.jpg
            wget $FOLDER/logo1.png
            wget $FOLDER/price.png
            systemctl start httpd
            systemctl enable httpd

Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
    Description: Honey-Flower Sale Application URL